### PR TITLE
dapple 0.8 migration

### PR DESCRIPTION
**Pull request by apmilen**
`dapple build` works fine but `dapple test` does not! It fails one test: `testAddBalance` in `balance_db_test.sol`. Here's the weird part, when I change the name to something else, like `testHooplah` then it passes but `testMoveBalance` fails! When I change that to `testHaaplah` then all the tests pass. I'm very confused and I created this remote branch so that someone else can test this condition with the same code.

### CODE REVIEW

**Comment by mhhf** [comment]
This might be the same bug as this: https://github.com/nexusdev/dapple-test/issues/3
bugfix is already on the way

**Comment by apmilen** [comment]
was this bugfix pushed in the latest npm publish? I'm still seeing this problem with the latest version

**Comment by mhhf** [comment]
On the way, as its outside of my responsibility and I'm discussing it with the ethereumjs folks: https://github.com/ethereumjs/ethereumjs-vm/issues/88
Unfortunately they are the bottleneck with this and I can't build workarounds here -.-

**Comment by apmilen** [comment]
Okay that sounds fine to me, but how confident are you that the problem I've encountered is caused by the ethereum-js issue you linked to?

**Comment by nmushegian** [comment]
did the merge, issue still persists in latest `master`, however it seems not to break things downstream

**Pull request closed without merging**
